[ClassVersion("1.0.0.0"), FriendlyName("xRDSessionCollectionMember")]
class MSFT_xRDSessionCollectionMember : OMI_BaseResource
{
    [key, Description("Specifies an RD Session Host server to managed in the session collection. ")] string SessionHost;
    [key, Description("Specifies a name for the session collection. ")] string CollectionName;
    [Write, Description("Specifies the Remote Desktop Connection Broker (RD Connection Broker) server for a Remote Desktop deployment.")] string ConnectionBroker;
    [Write, Description("Present if the RemoteApp should exist, Absent if it should be removed"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("Specifies if new connection are allowed or not"), ValueMap{"YES","NOUNTILREBOOT","NO"}, Values{"YES","NOUNTILREBOOT","NO"}] string NewConnectionAllowed;
};
